#!/usr/bin/env python
#Data request for "X" data to feed into machine-learning
from ecmwfapi import ECMWFDataServer
server = ECMWFDataServer()
server.retrieve({
    "class": "ea",
    "dataset": "era5",
    "date": "2008-01-01/to/2008-01-31"
    "expver": "1",
    "levtype": "sfc",
    "number": "0",
    "param": "168.128/167.128/134.128/228.128/165.128/166.128/66.128",
    "step": "6",
    "stream": "enda",
    "time": "06:00:00",
    "type": "fc",
    "target": "output",
})
